export const ADD_AWARDS = 'ADD_AWARDS';
export const AWARDS_LOADING = 'AWARDS_LOADING';
export const AWARDS_FAILED = 'AWARDS_FAILED';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';